-- Fixture for the M3 load test: one project holding 10,000 tasks.
--
-- Written as SQL and applied directly rather than driven through the API.
-- That is a deliberate choice and worth defending: M3 is a statement about
-- read latency at size, so the fixture is a precondition, not part of the
-- measurement. Creating ten thousand tasks over HTTP would take minutes,
-- measure the write path nobody is asking about, and make the run too slow to
-- repeat - and a benchmark nobody repeats is a benchmark nobody trusts.
--
-- Everything a read actually touches is populated: assignees, tags, checklist
-- items and comments, because the board hydrates all four. The search vector
-- is a generated column, so it fills itself.
--
-- Idempotent: running it twice replaces the fixture rather than doubling it.

\set ON_ERROR_STOP on

-- Fixed ids, so the k6 script can address the fixture without a lookup and a
-- re-run cleans up exactly what the previous one left.
\set project_id '''11111111-1111-4111-8111-111111111111'''

BEGIN;

-- Cascades through tasks, assignees, tags, checklist items and comments.
DELETE FROM projects WHERE id = :project_id;

INSERT INTO projects (id, name, key, description, status, owner_id, created_by)
SELECT :project_id, 'Load Test Project', 'LOADTEST',
       'Fixture for the M3 load test. Safe to delete.', 'active', u.id, u.id
  FROM users u
 WHERE u.role = 'admin' AND u.active
 ORDER BY u.created_at
 LIMIT 1;

INSERT INTO project_statuses (project_id, key, label, position, color) VALUES
    (:project_id, 'todo',        'To do',       0, '#94a3b8'),
    (:project_id, 'in_progress', 'In progress', 1, '#3b82f6'),
    (:project_id, 'review',      'Review',      2, '#f59e0b'),
    (:project_id, 'done',        'Done',        3, '#22c55e');

-- Twenty-five people. The workload and capacity reports fan out per person, so
-- the number matters: with one assignee those queries collapse to a shape they
-- never have in production.
INSERT INTO users (id, username, email, name, role, auth_source, password_hash, active, weekly_capacity_hours)
SELECT
    ('22222222-2222-4222-8222-' || lpad(n::text, 12, '0'))::uuid,
    'loadtest_user_' || n,
    'loadtest_user_' || n || '@example.com',
    'Load Test Person ' || n,
    'member', 'local',
    -- Never signed in as; the account exists to be assigned work.
    'x', true, 40
  FROM generate_series(1, 25) n
ON CONFLICT (id) DO NOTHING;

INSERT INTO project_members (project_id, user_id)
SELECT :project_id, ('22222222-2222-4222-8222-' || lpad(n::text, 12, '0'))::uuid
  FROM generate_series(1, 25) n
ON CONFLICT DO NOTHING;

-- --------------------------------------------------------------------------
-- The tasks
-- --------------------------------------------------------------------------
-- Titles carry varied vocabulary rather than one repeated string: a full-text
-- index over 10,000 identical titles has one posting list and answers every
-- query instantly, which would make the search measurement meaningless.
INSERT INTO tasks (
    id, title, description, project_id, status, priority,
    start_date, due_date, completed_at, estimate_hours, position, created_by, created_at
)
SELECT
    ('33333333-3333-4333-8333-' || lpad(n::text, 12, '0'))::uuid,
    (ARRAY['Migrate','Refactor','Document','Review','Deploy','Investigate','Fix','Design',
           'Benchmark','Rewrite'])[1 + (n % 10)]
      || ' ' ||
    (ARRAY['the billing importer','the audit trail','the search index','the kanban board',
           'the alert scheduler','the capacity report','the OIDC callback','the timeline view',
           'the retention sweep','the export pipeline'])[1 + ((n / 7) % 10)]
      || ' (#' || n || ')',
    'Generated by scripts/loadtest/seed.sql. Item ' || n || ' of the M3 fixture.',
    :project_id,
    (ARRAY['todo','in_progress','review','done'])[1 + (n % 4)],
    (ARRAY['low','medium','high','urgent'])[1 + (n % 4)],
    now() - ((n % 180) || ' days')::interval,
    now() + ((n % 90) - 30 || ' days')::interval,
    -- Only the done column carries a completion stamp, which is what the
    -- trend and progress aggregations read.
    CASE WHEN n % 4 = 3 THEN now() - ((n % 30) || ' days')::interval END,
    (n % 13) + 1,
    n,
    (SELECT id FROM users WHERE role = 'admin' AND active ORDER BY created_at LIMIT 1),
    now() - ((n % 365) || ' days')::interval
  FROM generate_series(1, 10000) n;

-- Most tasks have one assignee, every third has two. A task shared between two
-- people is the case the capacity report has to split rather than double-count,
-- so the fixture has to contain some.
INSERT INTO task_assignees (task_id, user_id)
SELECT ('33333333-3333-4333-8333-' || lpad(n::text, 12, '0'))::uuid,
       ('22222222-2222-4222-8222-' || lpad(((n % 25) + 1)::text, 12, '0'))::uuid
  FROM generate_series(1, 10000) n
ON CONFLICT DO NOTHING;

INSERT INTO task_assignees (task_id, user_id)
SELECT ('33333333-3333-4333-8333-' || lpad(n::text, 12, '0'))::uuid,
       ('22222222-2222-4222-8222-' || lpad((((n + 7) % 25) + 1)::text, 12, '0'))::uuid
  FROM generate_series(1, 10000, 3) n
ON CONFLICT DO NOTHING;

INSERT INTO task_tags (task_id, tag)
SELECT ('33333333-3333-4333-8333-' || lpad(n::text, 12, '0'))::uuid,
       (ARRAY['backend','frontend','infra','urgent','tech-debt'])[1 + (n % 5)]
  FROM generate_series(1, 10000) n
ON CONFLICT DO NOTHING;

-- Every fifth task carries a short checklist, and every fourth a comment. The
-- board hydrates both, so leaving them empty would measure a lighter page than
-- the one people actually open.
INSERT INTO task_checklist_items (id, task_id, text, done, position)
SELECT ('44444444-4444-4444-8444-' || lpad((n * 3 + i)::text, 12, '0'))::uuid,
       ('33333333-3333-4333-8333-' || lpad(n::text, 12, '0'))::uuid,
       'Step ' || i, i = 1, i
  FROM generate_series(1, 10000, 5) n, generate_series(1, 3) i;

INSERT INTO task_comments (id, task_id, author_id, body, created_at)
SELECT ('55555555-5555-4555-8555-' || lpad(n::text, 12, '0'))::uuid,
       ('33333333-3333-4333-8333-' || lpad(n::text, 12, '0'))::uuid,
       ('22222222-2222-4222-8222-' || lpad(((n % 25) + 1)::text, 12, '0'))::uuid,
       'Progress note on item ' || n || '.',
       now() - ((n % 60) || ' days')::interval
  FROM generate_series(1, 10000, 4) n;

-- --------------------------------------------------------------------------
-- Dependencies, so the critical path is actually walked
-- --------------------------------------------------------------------------
-- Without these the schedule endpoint answers an empty graph in under a
-- millisecond and the timeline measurement means nothing - which is exactly
-- the trap, because the backlog names that query as a plausible surprise.
--
-- The shape matters as much as the count. The walk is memoised over a directed
-- graph, so its cost is driven by the longest chain and by nodes reachable
-- along several routes, not by the number of edges. So the fixture builds
-- both: 400 chains of 5 links each (depth), plus diamonds where two
-- predecessors converge (re-visited nodes).
--
-- Every edge points from a higher n to a lower one, which makes a cycle
-- impossible by construction - the trigger would refuse one anyway, but a
-- fixture that relies on being rejected is a fixture that half-loaded.
INSERT INTO task_dependencies (task_id, depends_on_id, type, lag_days)
SELECT ('33333333-3333-4333-8333-' || lpad((base + step)::text, 12, '0'))::uuid,
       ('33333333-3333-4333-8333-' || lpad((base + step - 1)::text, 12, '0'))::uuid,
       'finish_to_start', 0
  FROM generate_series(1, 2000, 5) base, generate_series(1, 4) step
ON CONFLICT DO NOTHING;

-- Diamonds: a task waiting on two predecessors that share an ancestor, which
-- is the case a naive walk visits twice and a memoised one visits once.
INSERT INTO task_dependencies (task_id, depends_on_id, type, lag_days)
SELECT ('33333333-3333-4333-8333-' || lpad((base + 4)::text, 12, '0'))::uuid,
       ('33333333-3333-4333-8333-' || lpad((base + 1)::text, 12, '0'))::uuid,
       'finish_to_start', 0
  FROM generate_series(1, 2000, 5) base
ON CONFLICT DO NOTHING;

COMMIT;

-- The planner needs current statistics, or the first queries measure a table
-- it still believes is empty and choose sequential scans accordingly. Without
-- this the run reports the cost of a stale plan rather than of the schema.
ANALYZE tasks;
ANALYZE task_assignees;
ANALYZE task_tags;
ANALYZE task_checklist_items;
ANALYZE task_comments;
ANALYZE task_dependencies;

SELECT
    (SELECT count(*) FROM tasks WHERE project_id = :project_id)   AS tasks,
    (SELECT count(*) FROM task_dependencies d
       JOIN tasks t ON t.id = d.task_id
      WHERE t.project_id = :project_id)                           AS dependencies;
